# 1. Build React App
FROM node:18-alpine as builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# RUN npm run build

# # 2. Serve with Nginx
# FROM nginx:stable-alpine

# COPY nginx.conf /etc/nginx/nginx.conf
# COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 3000

# Start the development server
CMD ["npm", "start"]
# CMD ["nginx", "-g", "daemon off;"]
